name: Core Tests.

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10.14
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.14'
      - uses: actions/cache@v4
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('pyproject.toml') }}
      - name: Install dependencies
        run: |
          pip install uv
          uv pip install --system --upgrade -e .[dev]
          uv pip install waymo-open-dataset-tf-2-11-0==1.6.1
      - name: Check notebook cell metadata
        run: |
          python ./nerfstudio/scripts/docs/add_nb_tags.py --check
      - name: Run Ruff Linter
        run: ruff check docs/ nerfstudio/ tests/ --output-format=github
      - name: Run Ruff Formatter
        run: ruff format docs/ nerfstudio/ tests/ --diff
      - name: Test with pytest
        run: |
          pytest
